### ISSUE TITLE
Full restructure of sextalk

### ISSUE THREAD

**Issue by ErinaSugino** [ErinaSugino/Starbound-SBR-Mod#73]
The entire sextalk plugin has several severe flaws in design and execution and is in need of a rework.
The files are structured both too complicated for any normal user to understand and edit freely, aswell as too limited in complexity to reasonably cover all scenarios that are to be covered.
Actors are wildly trying to talk whenever they themselves are off cooldown despite only ever one at a time being able to display dialog.
Loading and, especially, merge vs. override mechanics are all over the place.

### File structure
The file structure needs to be reworked from the ground up to account for the new complexity of scenarios and also implement overriding mechanics and co. in a more user-friendly/editable manner.

The currently implemented draft for data structure is as follows:
```json
{
    "base": null, //Base dialog file to expand upon
    "add": false, //Whether this file adds to or overrides duplicates with it's base
    "content": {
        //Dialog per interaction type
        "<interaction_type>": ,
        "default": {
            //Dialog per state
            "climax": ,
            "preclimax": ,
            "postclimax": ,
            "sex": {
                //Dialog per partner state
                "climax": ,
                "preclimax": ,
                "postclimax": ,
                "sex": {
                    "<partner_species>": ,
                    "default": {
                        "override": true, //Whether or not this overrides the "default" species dialog.
                        //Dialog per partner species
                        "text": [
                            "Ah."
                        ],
                        "status": {
                            //Status specific dialog based on our statuses
                            "pregnant": {
                                "override": false, //Defines if this adds to or overrides text from state combo
                                "priority": 10, //Defines order in which statuses are applied
                                "text": [
                                    "Big Ah."
                                ]
                            }
                        },
                        "otherStatus": {
                            //Status specific dialog base on partner's statuses
                            "pregnant": {
                                "override": false, //Defines if this adds to or overrides text from state combo
                                "priority": 10, //Defines order in which statuses are applied
                                "text": [
                                    "Bigger Ah."
                                ]
                            }
                        },
                        "bothStatus": {
                            //Status specific dialog based on statuses both partner's have
                            "pregnant": {
                                "override": false, //Defines if this adds to or overrides text from state combo
                                "overrideSoloStatus": false, //Defines if this adds to or adds same-status "status" and "otherStatus"
                                "priority": 10, //Defines order in which statuses are applied
                                "text": [
                                    "The biggest Ah"
                                ]
                            }
                        }
                    }
                }
            }
        }
    }
}
```
With the following data accounted for:
```
> CORE
- Position
- Interaction Type
- Partner Species

> STATE
- Sex
- Pre-climax
- Climax
- Post-climax

> STATUS
- Pregnant
- Heat
- Defeated
- Has Penis
- Has Vagina

> OPTIONAL
- Priority

Interaction Types:
vaginal
r_vaginal
anal
r_anal
oral
r_oral
cunnilingus_vagina
cunnilingus_ass
r_cunnilingus
boobjob
r_boobjob
masturbate_penis
masturbate_vagina
toy_vagina
toy_in_vagina
toy_in_ass
```

### Code changes
Besides the obvious need of drastic changes to load and support the changed file structure from above, the entire concept of the sextalk plugin needs to be reworked. The logic that handles who talks when and also supports the individual actors with the state information they need to choose the right dialog options needs to be outsourced into a higher level (sexbound.lua) centralized manager. That way, the amount of checks and communication done to determine who talks when is drastically reduced.

### Todos
- [x] Restructure files
- [x] Transform existing dialog into new structure
- [x] Outsource sextalk managing
- [x] Update sextalk actor plugin to accomodate all above changes
